
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rainier
 */
public class Calculator extends javax.swing.JFrame {

    //private int k;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        inputPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        arrayText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        solveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayAnswers1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        uploadFileButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayAnswers = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subset Sum Calculator");

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 1, 36)); // NOI18N
        jLabel4.setText("Subset Sum Calculator");

        jLabel1.setText("Enter Sum:");

        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        arrayText.setColumns(20);
        arrayText.setRows(5);
        jScrollPane1.setViewportView(arrayText);

        jLabel3.setText("(must be ");

        solveButton.setText("Solve!");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Set:");

        jLabel5.setText("comma-separated)");

        jLabel7.setText("Subset Sums:");

        displayAnswers1.setColumns(20);
        displayAnswers1.setRows(5);
        jScrollPane3.setViewportView(displayAnswers1);

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel7))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(solveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(solveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Input Set", inputPanel);

        uploadFileButton.setText("Upload File...");
        uploadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileButtonActionPerformed(evt);
            }
        });

        fileNameLabel.setText("...");

        jLabel6.setText("Subset Sums:");

        displayAnswers.setColumns(20);
        displayAnswers.setRows(5);
        jScrollPane2.setViewportView(displayAnswers);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uploadFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileNameLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel6)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uploadFileButton)
                    .addComponent(fileNameLabel))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Load File", jPanel1);

        jLayeredPane2.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        // TODO add your handling code here:
        int k = Integer.parseInt(sum.getText());
        String temp = arrayText.getText();
        String[] temp2 = temp.split(",");
        int size = temp2.length;
        int[] set = new int[size];

        //needs idiotproofing
        for(int i = 0; i < size; i++){
            set[i] = Integer.parseInt(temp2[i]);
        }
        ArrayList<ArrayList<Integer>> combinationArray = Combination(size);
        ArrayList<int[]> answerArray = FindSubsetSum(combinationArray, k, set);
//        String []columns = new String[]{"Answers"};
        String textToDisplay = "";
        for(int i = 0; i < answerArray.size() ; i++){
           for(int j=0; j< answerArray.get(i).length ; j++){
              if(answerArray.get(i)[j] == 0) continue;
              if(j != answerArray.get(i).length-1)textToDisplay += (Integer.toString(answerArray.get(i)[j])+ " ");
              else textToDisplay += Integer.toString(answerArray.get(i)[j]);
           }textToDisplay += "\n";
       }
        displayAnswers1.setText(textToDisplay);

    }//GEN-LAST:event_solveButtonActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumActionPerformed

    private void uploadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only .txt files", "txt", "text");
        j.setFileFilter(filter);
        int r = j.showSaveDialog(null);
        // if the user selects a file 
        if (r == JFileChooser.APPROVE_OPTION){ 
            // set the label to the path of the selected file 
            fileNameLabel.setText(j.getSelectedFile().getAbsolutePath()); 
            String filename = j.getSelectedFile().getAbsolutePath();
        File f = new File(filename);
        try { 
            FileReader fileReader = new FileReader(f);
            BufferedReader bReader = new BufferedReader(fileReader);
            String line = bReader.readLine();
            int numOfSets = Integer.parseInt(line);
            System.out.println(numOfSets);
            int arrayOfSums[] = new int[numOfSets];
            ArrayList<int []> arrayOfSets = new ArrayList<>(); 
            for(int i = 0; i < numOfSets; i++){
                line = bReader.readLine();
                if(line.equals("")) break;
                arrayOfSums[i] = Integer.parseInt(line);
                line = bReader.readLine();
                String lines[] = line.split(" ");
                int[] tempArray = new int[lines.length];
                int k = 0;
                for (String line1 : lines) {
                    tempArray[k] = Integer.parseInt(line1);
                    k++;
                }arrayOfSets.add(tempArray);
                
            }
            ArrayList<int[]> answerArray = null;
            String textToDisplay = "";
            for(int i = 0; i < numOfSets; i++){
                answerArray = FindSubsetSum(Combination(arrayOfSets.get(i).length), arrayOfSums[i], arrayOfSets.get(i));
                textToDisplay = textToDisplay+ "Sums of "+ Integer.toString(arrayOfSums[i]) +":\n";
                for (int b = 0; b < answerArray.size(); b++) {
                    for (int x = 0; x < answerArray.get(b).length; x++) {
                        if(answerArray.get(b)[x] == 0) continue;
                        if (x != answerArray.get(b).length - 1) {
                            textToDisplay += (Integer.toString(answerArray.get(b)[x]) + " ");
                        } else {
                            textToDisplay += Integer.toString(answerArray.get(b)[x]);
                        }
                    }
                    textToDisplay += "\n";
                }textToDisplay += "\n";
            }
            
        
            displayAnswers.setText(textToDisplay);
            System.out.println(textToDisplay);
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else fileNameLabel.setText("No file chosen..."); 
        
    }//GEN-LAST:event_uploadFileButtonActionPerformed
    
    private ArrayList<int[]> FindSubsetSum(ArrayList<ArrayList<Integer>> combination, int sum, int[] set){
       ArrayList<int[]> subsetSums= new ArrayList<>();
       
        for(int i = 0; i < combination.size() ; i++){
           int tempSum = 0;
           int[] tempArray = new int[combination.get(i).size()];
           for(int j=0; j< combination.get(i).size() - 1 ; j++){
               tempSum+= set[combination.get(i).get(j) - 1];
               tempArray[j] = set[combination.get(i).get(j) - 1];
           }
           if(tempSum == sum){
               subsetSums.add(tempArray);
           }
       }
        return subsetSums;
    }
    
    private ArrayList<ArrayList<Integer>> Combination(int size){
        ArrayList<ArrayList<Integer>> combinations = new ArrayList<>();
        int start, move, i, candidate;
        int nopts[] = new int[size+2];
        int option[][] = new int[size+2][size+2];
        
        start= move=0;
        nopts[start]=1;
        
        while(nopts[start]>0){
            if(nopts[move]>0){
                move++;
                nopts[move]=0;
                
                if(move != size+1){
                    for(candidate=size ; candidate>=1 ; candidate--){
                        for(i=move-1;i>=1;i--){
                            if(candidate >= option[i][nopts[i]]){break;}
                        }
                        if(!(i>=1)){
                            option[move][++nopts[move]]=candidate;
                        }
                    }
                }
            }else{
                ArrayList<Integer> tempArray= new ArrayList<>();
                for(i=1;i<move;i++){
                    tempArray.add(option[i][nopts[i]]);
                }
                if(!tempArray.isEmpty()){
                    combinations.add(tempArray);
                }
                move--;
                nopts[move]--;
            }
        }
        return combinations;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arrayText;
    private javax.swing.JTextArea displayAnswers;
    private javax.swing.JTextArea displayAnswers1;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton solveButton;
    private javax.swing.JTextField sum;
    private javax.swing.JButton uploadFileButton;
    // End of variables declaration//GEN-END:variables
}
